baseURL = "/"
languageCode = "en-us"
title = "endomer"
Paginate = 1000
googleAnalytics = ""
theme = "showcase-hugo-theme"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "endomer"
  description = "Página web principal del proyecto Encuestas Dominicanas en R (endomer)"
  message = "Es un proyecto que busca proveer herramientas útiles para trabajar con bases de datos de encuestas dominicanas en R."
  hideAutoMenu = false

[social]
  twitter = "https://twitter.com/search?q=%23endomer&src=typed_query"
  github = "https://github.com/endomer"
